### ISSUE TITLE
How to compile mesa + setup virgl?

### ISSUE THREAD

**Issue by xDoge26** [Pipetto-crypto/Chroot-Docs#2]
btw can i use prebuilt mesa from exagear ?

**Comment by Pipetto-crypto** [comment]
I can't tell for sure but it should work else you will have to compile an armhf 32bit variant of it if you are trying to get mesa for box86. You will have to install an armhf cross compiler like gcc-arm-linux-gnueabihf( sudo apt install gcc-arm-linux-gnueabihf).

Then override default compiler like this during compilation:

CC=arm-linux-gnueabihf-gcc CXX=arm-linux-gnueabihf-g++ meson . build -Dgallium-va=false -Ddri-drivers= -Dgallium-drivers=virgl,swrast -Ddri3=false -Dvulkan-drivers= -Dglx=xlib -Dplatforms=x11,wayland -Dtools=

Else what I recommend is to try to use the libGL.so.armv7.1 you can find here https://github.com/mittorn/virglrenderer-android/releases

Create a lib folder into your home directory, move the libGL.so.armv7.1 there and then:

export LD_LIBRARY_PATH=~/lib

export BOX86_LD_LIBRARY_PATH=$BOX86_LD_LIBRARY_PATH:~/lib

EDIT: Newer mesa version sources won't compile because of missing dependencies, you will need to compile and install these:


    https://gitlab.freedesktop.org/glvnd/libglvnd
    https://dri.freedesktop.org/libdrm
    https://gitlab.freedesktop.org/wayland/wayland
    https://gitlab.freedesktop.org/wayland/wayland-protocols

Before compiling mesa

**Comment by ikmjssc** [comment]
i thought exagear was (qemu)x86 unbuntu since wine is not an emulator. 
prebuilt mesa isn't going to work, but how's it going ? what's your results ?

**Comment by Pipetto-crypto** [comment]
>

**Comment by Pipetto-crypto** [comment]
> i thought exagear was (qemu)x86 unbuntu since wine is not an emulator. prebuilt mesa isn't going to work, but how's it going ? what's your results ?

exagear is a x86 to arm emulator similiar to box86. The latter though warps opengl with native libraries that's why x86 mesa binaries may not work and you may need to compile armhf mesa. But like I said I am not sure since I didn't try to use the precompiled mesa binaries from exagear.

 I haven't tested hardware acceleration because none of the phones I own are compatible with virgl

**Comment by ikmjssc** [comment]
tried to compile arm64 version. just showed a small black screen with glmark2(arm64 kali chroot). looks like mine is not compatible with virgl too(or some strange issus)
btw, why bother using termux:x11 without hardware acceleration ? just wondering

**Comment by Pipetto-crypto** [comment]
> tried to compile arm64 version. just showed a small black screen with glmark2(arm64 kali chroot). looks like mine is not compatible with virgl too(or some strange issus) btw, why bother using termux:x11 without hardware acceleration ? just wondering

Virgl compatibility is very low, better to use turnip+zink combo if you have an Adreno GPU, it should be way faster.

Termux:X11 is quite faster for me, especially when watching videos

**Comment by ikmjssc** [comment]
> 

tried that x11... sometimes it launched sometimes not though i executed the same script. also tried turnip but it seems they don't support adreno a7xx. no luck

**Comment by Pipetto-crypto** [comment]
> > 
> 
> tried that x11... sometimes it launched sometimes not though i executed the same script. also tried turnip but it seems they don't support adreno a7xx. no luck

The fact that sometimes it doesn't launch happens to me as well. You need to stay in the app until you see a "Service created" toast appear. If this toast appears but it still doesn't launch, you need to force close both termux and termux-x11 app from Android settings and then retry.
The issue is that this app doesn't have a proper way to kill itself as of now from termux sadly but looking at the issues the devs are going to implement it soon

**Comment by ikmjssc** [comment]
> > > 
> > 
> > 
> > tried that x11... sometimes it launched sometimes not though i executed the same script. also tried turnip but it seems they don't support adreno a7xx. no luck
> 
> The fact that sometimes it doesn't launch happens to me as well. You need to stay in the app until you see a "Service created" toast appear. If this toast appears but it still doesn't launch, you need to force close both termux and termux-x11 app from Android settings and then retry. The issue is that this app doesn't have a proper way to kill itself as of now from termux sadly but looking at the issues the devs are going to implement it soon

We had the same thought. Termux:x11 has promising future(just like mesa) but it is not very stable at the moment(compare to VNC or even XSDL). After a dozen of force closes I switched back to VNC. But for sure,  Termux:x11 is really fast. VNC has some lags.

**Comment by xDoge26** [comment]
Do vnc work with virgl ?

**Comment by Pipetto-crypto** [comment]
> Do vnc work with virgl ?

Yea, it should work

**Comment by xDoge26** [comment]
> Yea, it should work

when i add these line to ect profile
 `export GALLIUM_DRIVER=virpipe`
`export LIBGL_ALWAYS_SOFTWARE=1`
tigervnc fail to boot

​

**Comment by Pipetto-crypto** [comment]
> > Yea, it should work
> 
> when i add these line to ect profile `export GALLIUM_DRIVER=virpipe` `export LIBGL_ALWAYS_SOFTWARE=1` tigervnc fail to boot
> 
> ​

Download virgl_overlay https://www.mediafire.com/file/2c3deplta6ao0zj/virgl-overlay-rebuild-v.0.0.8-gen_signed.apk and install it.

Open the app and in socket path put /data/data/com.mittorn.overlay/files/.virgl_test 

Enable the option "use opengl es 3.x instead of opengl" then start service.

Start the chroot and start the vnc server (remove those export GALLIUM_DRIVER and LIBGL stuffs from your /etc/profile) then inside termux, not the chroot paste these commands:

touch /data/local/mnt/tmp/.virgl_test

sudo mount --bind /data/data/com.mittorn.overlay/files/.virgl_test  /data/local/mnt/tmp/.virgl_test

Now, go inside vnc viewer and paste these commands in a terminal:

export GALLIUM_DRIVER=virpipe
export LIBGL_ALWAYS_SOFTWARE=1

By the way, if you have a Snapdragon with an Adreno 6xx GPU you can use turnip and zink

**Comment by xDoge26** [comment]
>/data/local/mnt/tmp/.virgl_test

what folder is this

**Comment by Pipetto-crypto** [comment]
> > /data/local/mnt/tmp/.virgl_test
> 
> what folder is this

That's the tmp folder of your chroot, /data/local/mnt is instead the folder where Linux Deploy usually mount the linux.img chroot into before chrooting into it

**Comment by ThieuMinh26** [comment]
> That's the tmp folder of your chroot, /data/local/mnt is instead the folder where Linux Deploy usually mount the linux.img chroot into before chrooting into it

touch /data/local/mnt/tmp/.virgl_test
~ $ sudo mount --bind /data/data/com.mittorn.overlay/files/.virgl_test /data/local/mnt/tmp/.virgl_test
mount: '/data/data/com.mittorn.overlay/files/.virgl_test'->'/data/local/mnt/tmp/.virgl_test': No such file or directory

**Comment by xDoge26** [comment]
hmm i cant run virgl with prebuilt mesa , i used linux deploy mount option instead termux  . but with `VTEST_SOCK=/tmp/.virgl_test box86 wine SphereMap.exe`  i keep getting lost connect to virgl no matter what i tried

**Comment by Pipetto-crypto** [comment]
> hmm i cant run virgl with prebuilt mesa , i used linux deploy mount option instead termux . but with `VTEST_SOCK=/tmp/.virgl_test box86 wine SphereMap.exe` i keep getting lost connect to virgl no matter what i tried

Can you do ls -l /tmp/.virgl_test to see if this file exists properly? If it does it should have srwxrwxrwx permissions. If it's not like this you haven't mounted it properly then you can't use linux deploy mount option since you have to mount it after you create the socket with the virgl overlay app that you installed from the apk

**Comment by xDoge26** [comment]
> Can you do ls -l /tmp/.virgl_test to see if this file exists properly? If it does it should have srwxrwxrwx permissions. If it's not like this you haven't mounted it properly then you can't use linux deploy mount option since you have to mount it after you create the socket with the virgl overlay app that you installed from the apk

can you help me using anydesk,  keep getting mount error

**Comment by Pipetto-crypto** [comment]
> > Can you do ls -l /tmp/.virgl_test to see if this file exists properly? If it does it should have srwxrwxrwx permissions. If it's not like this you haven't mounted it properly then you can't use linux deploy mount option since you have to mount it after you create the socket with the virgl overlay app that you installed from the apk
> 
> can you help me using anydesk, keep getting mount error

I have never used this software so no I can't help you with that
